In [11]:
import numpy as np

A = np.array([[2, 1], [5, 3]])
B = np.array([[1, 0], [1, 1]])
C = np.array([[3, -1], [-5, 2]])

(A @ B @ C) @ (A @ B @ C) @ (A @ B @ C) @ (A @ B @ C) @ (A @ B @ C) @ (A @ B @ C)

array([[ 19,  -6],
       [ 54, -17]])

In [3]:
np.array([[ 4, -1],
          [ 9, -2]])**5

array([[ 1024,    -1],
       [59049,   -32]])

In [8]:
n = 5
np.array([[4 + 3*(n-1), -n], [9*n, -2-3*(n-1)]])

array([[ 16,  -5],
       [ 45, -14]])