# Линейная алгебра. Лабораторная работа 1, осень 2023

В этой лабораторной работе вы познакомитесь со средой Jupyter Notebook и библиотеками numpy и scipy.

## Часть 1. Библиотеки(10 баллов)

> Блок с отступами



В этой лабораторной работе вам понадобятся три библиотеки:

---



---



- `numpy` - основная библиотека для работы с многомерными массивами и матрицами, а также для выполнения операций линейной алгебры. Она предоставляет высокопроизводительные структуры данных и функции для работы с числовыми массивами;
- `sympy`, - это библиотека символьной математики для Python. Она предоставляет инструменты для символьных вычислений, включая символьное дифференцирование, интегрирование, алгебру и т. д. SymPy позволяет работать с математическими выражениями такими, как символьные переменные, уравнения и функции, в отличие от NumPy, который работает в основном с числовыми массивами.
- `matplotlib` - библиотека для отрисовки графиков

Подключить их можно следующим образом:

In [1]:
# Запустите этот код
from typing import List, Union

import numpy as np
import sympy as sp
import matplotlib.pyplot as plt

In [2]:
m = np.array([
    [1, 2, 3, 4],
    [0, 0, 0 ,0],
    [5, 6, 7, 7]
])

Обратите внимание, что матрица заполняется *по строкам*.
- `np.array(obj, dtype, ...)` - преобразование из списка, кортежа, генератора, другого массива, ...
    - `obj` - объект, который нужно преобразовать
    - `dtype` - тип элемента массива

Есть и много других конструкторов матриц. Например, единичная матрица размера $n\times n$ создаётся с помощью функции `numpy.eye(n)` или при помощи функции `sympy.eye(n)`, некоторые функции numpy аналогичны функциям sympy.
Попробуйте проверить это утверждение на практике, посмотрите, чем отличаются стандартные функции двух библиотек и в чем отличие функций для работы с матрицами.

In [5]:
np.all(m == 0, axis=1)
#Показывает, все ли значения вдоль оси (0 -  в столбце, 1 - в строке) имеют значения True

array([False,  True, False])

In [6]:
# преобразование из генератора списка, создает вектор
np.array([x**2 for x in range(13)])

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [7]:
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

Зачастую бывает нужно получить доступ к подматрицам данной матрицы, и numpy предоставляет множество удобных средств, как это сделать (называется slicing):
- элемент с номером `(i,j)`: `A[i,j]`
- i-я строка матрицы: `A[i,:]`
- j-й столбец матрицы: `A[:,j]`

    
- срез не копирует часть массива, а создает новое представление `view`, через которое можно как считывать, так и записывать значения элементов части исходного массива(в данном случае матрицы - двумерного массива)


**Внимание!** Оба варианта, и `A[i,:]`, и `A[:,j]` дают не строку или столбец, а одномерный вектор. Если вы хотите получить вектор-строку или вектор-столбец соответственно, используйте вот такой синтаксис: `A[i:i+1,:]`, и `A[:,j:j+1]`
- строки с нулевой по i-ю: `A[:i+1,:]`
- столбцы с j-го по последний: `A[:,j:]`
- строки с i-й по k-ю: `A[i:k,:]`

В некоторых случаях нужно получить доступ к (прямоугольной) подматрице, элементы которой находятся на пересечении строк из списка `rows` и столбцов `columns`. В этом случае `A[rows, columns]` даст не то, что вы ожидаете (можете попробовать это сделать сами и увидеть, что получится; только возьмите `rows` и `columns` одного размера). Справиться с этой задачей позволяет код `A[np.ix_(rows, columns)]`.

In [8]:
i = 0
j = 1
M[[i, i + j]] = M[[i + j, i]]

In [9]:
M[[i, i + j]]

array([[4, 5, 6],
       [1, 2, 3]])

In [10]:
M

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [11]:
M[[i + j, i]]

array([[1, 2, 3],
       [4, 5, 6]])

*Умножение матриц* производится с помощью оператора `np.dot()` или оператора `@`. Есть варианты написания: `A.dot(B)`, `np.dot(A, B)`, `A @ B`.

Обычные знаки арифметических действий (`+`, `-`, `*`) зарезервированы для поэлементных операций. Например, `A * B` &mdash; это матрица, элементами которой являются произведения $A_{ij}B_{ij}$. Помимо этих есть и множество других поэлементных операций. Например, `numpy.exp(A)` &mdash; это матрица, элементами которой являются экспоненты элементов матрицы `A`.

Чтобы получить матрицу, *транспонированную* к матрице `A`, напишите просто `A.T`.

В некоторых случаях бывает нужно создавать *случайные матрицы*: например, при проведении экспериментов или для инициализации итеративных методов. Средства для этого предоставляет пакет [numpy.random](https://docs.scipy.org/doc/numpy/reference/routines.random.html). Так, `np.random.rand(m,n)` &mdash; это матрица $m\times n$, элементы которой независимо выбраны из равномерного распределения на интервале `[0;1)`. Задание на интерес, есть ли аналогичная функция в `sympy`, если есть, то какая?

Для *решения систем линейных уравнений* в пакете `sympy.matrices` есть множество методов, рассмотрение которых выходит за пределы курса линейной алгебры. Мы вам пока предлагаем пользоваться функцией [sympy.matrices.matrices.MatrixBase.solve()](https://docs.sympy.org/latest/modules/matrices/matrices.html#sympy.matrices.matrices.MatrixBase.solve), функция может использовать несколько различных методов, которые перечислены по этой справочной ссылке API. В зависимости от характера матрицы тот или иной метод может быть более эффективным. По умолчанию будет использоваться метод исключения Гаусса-Жордана.

Указание метода в решении эквивалентно использованию специализированной решающей функции. Например, используя solve совместно с method=`LU` вызовает `LUsolve()`.

Полезные ссылки:

[ссылка на документацию библиотеки sympy](https://www.sympy.org/en/index.html)

[ссылка на пакет sympy.matrices](https://docs.sympy.org/latest/guides/solving/solve-matrix-equation.html)

**Перейдем к заданиям**

В качестве первого задания мы попросим вас отыскать соответствующие функции в библиотеке и сделать следующее:

- создайте нулевую матрицу $Z$ размера $3\times4$;

- создайте диагональную матрицу $5\times5$ с диагональными элементами 1, 2, 3, 4 и 5;

- найдите её след (не силою мысли, а с помощью библиотечных функций, конечно);

- найдите обратную к ней матрицу;

- сгенерируйте случайную матрицу $X$ размера $4\times5$;

- найдите определитель подматрицы матрицы $X$, расположенной на пересечении 2 и 3 строки и 1 и 2 столбца; считаем, что строки и столбцы нумеруются с единицы (используйте slicing!). Такой определитель называется **минором** матрицы $X$;

- найдите произведение $X^TX$.

Пожалуйста, каждый пункт делайте в новом блоке и не забывайте распечатывать результаты. Задания необходимо сделать как с помощью `numpy`, так и с помощью
`sympy`.

In [ ]:
# Your code here


## Часть 2. Точность(5 баллов)

Наверняка вы уже что-то знаете про floating point arithmetics и связанные с этим трудности и понимаете, что на компьютере вычисления с вещественными числами производятся лишь с ограниченной точностью.

В качестве первого примера, показывающего различие между длинной арифметикой целых чисел и floating point arithmetics, предлагаем вам перемножить две пары матриц:

$$
\begin{pmatrix}
1 & 0\\
10^{20} & 1
\end{pmatrix}
\cdot
\begin{pmatrix}
10^{-20} & 1\\
0 & 1 - 10^{20}
\end{pmatrix}
$$
и
$$
\begin{pmatrix}
1. & 0.\\
10.^{20} & 1.
\end{pmatrix}
\cdot
\begin{pmatrix}
10.^{-20} & 1.\\
0. & 1. - 10.^{20}
\end{pmatrix}
$$
Во втором случае мы специально указали Питону (поставив везде десятичные точки), что хотим работать не с целыми числами, а с числами с плавающей точкой. Посмотрим, получатся ли одинаковые ответы:

In [ ]:
# Your code here

И какой из них правильный?

---
**Напишите здесь свой ответ**

## Часть 3. Матричные вычисления(10 баллов)

---



Как вы уже заметили, в питоне лучше избегать испольизование циклов, применяя библиотечные функции, они быстрее работают и код выглядит более компактным.

В качестве примера рассмотрим две задачи:

**1.** Предположим, нужно вычислить суммы элементов в каждой строке матрицы `A`. Ясно, что можно написать простую функцию с двумя циклами, которая это посчитает, но так лучше не делать. Правильный способ такой:
```
A.sum(axis=1)
```
Параметр `axis=1` означает, что суммы берутся по строкам. Если вы хотите просуммировать по столбцам, укажите `axis=0`. Если вообще пропустить параметр `axis` (вызвать `A.sum()`), то функция вернёт сумму *всех* элементов матрицы.

**2.** Теперь допустим, что нам нужно каждый столбец матрицы `A` умножить на некоторое число. Более точно, пусть у нас есть (одномерный) вектор `w = np.array([w_1,...,w_n])`, и мы должны `i`-й столбец `A` умножить на число `w_i`. Опять же, это можно сделать в пару циклов, но лучше использовать операцию поэлементного умножения:
```
A * w.reshape((1,n))
```
Оператор `reshape` нужен для того, чтобы из одномерного вектора сделать вектор-строку.

Аналогично, если на числа `w_1,...,w_n` умножаются *строки* матрицы, нужно превратить `w` в вектор-столбец:
```
A * w.reshape((n,1))
```

Дальше вам будет предложено попрактиковаться в матричных вычислениях. В следующих трёх заданиях нельзя пользоваться циклами, а также конструкциями `map` и `reduce` и им подобными; вместо этого постарайтесь свести всё к матричным операциям из `numpy` (но, опять же, не `np.vectorize` или чему-то подобному). Чтобы убедиться, что получилось именно то, что нужно, пишите собственные тесты со случайными матрицами.

Не забудьте написать тесты, которые будут проверять корректность ваших функций.

**Задание 4.1** Напишите функцию `prod_and_sq_sum(A)`, вычисляющую произведение и сумму квадратов диагональных элементов квадратной матрицы `A`.

**Задание 4.2** Для матриц `A` и `B` размера $m\times n$ обозначим через $a_1,\ldots,a_n$ и $b_1,\ldots,b_n$ соответственно их столбцы. Напишите функцию `f(A, B, k)`, вычисляющую

$$\sum_{i=1}^{\min(k,m)}a_ib_i^T$$

**Задание 4.3** Напишите функцию `get_diag(A,B)`, принимающую две квадратных матрицы `A` и `B` одного размера и возвращающую вектор диагональных элементов произведения `AB`, не вычисляя произведение целиком.

## Часть 4. Метод Гаусса(20 баллов)

В этом разделе вам предстоит самостоятельно написать функции, которые позволят вам применить метод Гаусса в решении СЛАУ. Далее, вы опробуете их в действии.



Небольшое теоретическое напоминание.
Типы элементарных преобразований над матрицами:


1.   Перестановка местами двух любых строк матрицы
2.   Прибавление к любой строке матрицы другой строки, помноженной на константу
3.   Умножение любой строки матрицы на константу `k`, `k != 0`(Что в этом случае становится с определителем матрицы?)


Напишите три функции для каждого из методов, которые принимают на вход матрицу $A$ $n\times m$: sp.Matrix

1.   `swap_rows` - возвращает матрциу с переставленными двумя строками
`swap i, j`
2.   `multiply_row` - возвращает матрицу с выбранной строкой помноженной на константу - `i := i * lambda, lambda != 0`
3.   `multiply_and_add_rows` - возвращает матрицу с умноженной строкой на константу и прибавлением ее к другой - `i := i + lambda * j`

Обязательно проверьте, правильно ли работают ваши функции.



In [97]:
def swap_rows(A: sp.Matrix, i: int, j: int):
    A[i, :], A[j, :] = A[j, :], A[i, :]
    return A

swap_rows(sp.Matrix([[1, 2, 3, 4], [2, 3, 4, 5]]), 0, 1)

Matrix([
[2, 3, 4, 5],
[1, 2, 3, 4]])

In [99]:
def multiply_row(A: np.array, i: int, ro: float):
    A[i, :] = ro * A[i, :]
    return A

multiply_row(sp.Matrix([[1, 2, 3, 4], [2, 3, 4, 5]]), 1, 1/100)

Matrix([
[   1,    2,    3,    4],
[0.02, 0.03, 0.04, 0.05]])

In [103]:
def multiply_and_add_rows(A: np.array, i: int, j: int, ro: float):
    A[i, :] = A[i, :] + ro * A[j, :]
    return A

multiply_and_add_rows(sp.Matrix([[1, 2, 3, 4], [2, 3, 4, 5]]), 0, 1, 1/200)

Matrix([
[1.01, 2.015, 3.02, 4.025],
[   2,     3,    4,     5]])

Разобравшись с преобразованиями матриц, перейдем к решению СЛАУ.
На семинаре вы познакомились с методом Гауса, он является наиболее быстрым методом, как для написания программ, так и для вычисления ручками. Сейчас вы попробуете реализовать этот метод.

Вам необходимо самостоятельно написать код, который будет реализовывать прямой и обратный проход алгоритма гаусса, используйте функции элементарных преобразований над матрицами, что вы написали ранее. Учтите, что решений может быть множество, одно или не быть вовсе. Сравните свое решение со встроенной функцией библиотеки sympy.



In [134]:
def gaussian_elimination(A, b):
    """
    Метод Гаусса для решения СЛАУ Ax = b.

    Параметры:
    A -- матрица коэффициентов системы уравнений (np.array)
    b -- вектор правой части (np.array)

    Возвращает:
    верхнетреугольную матрицу M.
    """
    S = np.hstack([A, b])
    zeros_down = np.all(S == 0, axis=1).argsort()
    S = S[zeros_down].astype(float)
    for anchor_row in range(S.shape[0]):
        zero_mask = (S[anchor_row] == 0)
        if np.all(zero_mask):
            break
        anchor_col = np.argwhere(~zero_mask).ravel()[0]
        anchor_elem = S[anchor_row, anchor_col]
        S = multiply_row(S, anchor_row, 1/anchor_elem)
        for j in range(anchor_row + 1, S.shape[0]):
            S = multiply_and_add_rows(S, j, anchor_row, -S[j, anchor_col])

    last_non_zero_row = anchor_row
    for anchor_row in range(last_non_zero_row, -1, -1):
        zero_mask = (S[anchor_row] == 0)
        if np.all(zero_mask):
            break
        anchor_col = np.argwhere(~zero_mask).ravel()[0]
        anchor_elem = S[anchor_row, anchor_col]
        S = multiply_row(S, anchor_row, 1/anchor_elem)
        for j in range(anchor_row - 1, -1, -1):
            S = multiply_and_add_rows(S, j, anchor_row, -S[j, anchor_col])
    return S

Ниже вы видите примеры. Проведите тесты и убедитесь, что решение получилось верным.

In [164]:
one_solution = [
    {
        'A': np.array([[2, -3], [4, 1]]),
        'b': np.array([7, 2])[:, None]
    },
    {
        'A': np.array([[1, 2, -1], [2, -1, 3], [3, 1, -2]]),
        'b': np.array([4, 9, 1])[:, None]
    },
    {
        'A': np.array([[1, 2, -1, 3],
                       [2, 3, 1, -2],
                       [3, 0, -1, 4],
                       [4, 1, 1, 1]]),
        'b': np.array([10, 5, 12, 8])[:, None]
    }
]

no_solutions = [
    {
        'A': np.array([[2, -3], [4, -6]]),
        'b': np.array([7, 12])[:, None]
    },
    {
        'A': np.array([[1, 2, -1], [2, 4, -2]]),
        'b': np.array([4, 9])[:, None]
    },
    {
        'A': np.array([[1, 1, -1, 3],
                       [2, 2, 1, -2],
                       [3, 3, 4, 1],
                       [4, 4, 1, 1]]),
        'b': np.array([10, 5, 12, 6])[:, None]
    }
]

infinite_solutions = [
    {
        'A': np.array([[2, 3], [4, 6]]),
        'b': np.array([6, 12])[:, None]
    },
    {
        'A': np.array([[1, -2], [2, -4]]),
        'b': np.array([5, 10])[:, None]
    },
    {
        'A': np.array([[1, 2, -1, 3],
                       [2, 4, -2, 6],
                       [3, 6, -3, 9],
                       [4, 8, -4, 12]]),
        'b': np.array([8, 16, 24, 32])[:, None]
    }
]

In [165]:
for d in one_solution + no_solutions + infinite_solutions:
    my_ans = gaussian_elimination(d['A'], d['b'])
    augmented_matrix = sp.Matrix.hstack(sp.Matrix(d['A']), sp.Matrix(d['b']))
    sympy_ans, pivot_cols = sp.Matrix.rref(augmented_matrix)
    sympy_ans = np.array(sympy_ans.tolist()).astype(np.float64)
    assert np.allclose(np.array(sympy_ans), my_ans)

Получите из верхнетругольной матрицы решение системы в функции get_solutions.
Для этого, вы должны посмотреть на то, какой получилась верхнетреугольная матрица, вспомните, что если в результате элементарных преобразований получена строка вида `(0, 0, 0.....0|α)`, где  – число, отличное от нуля, то система несовместна (не имеет решений). В этом случае нет смысла продолжать алгоритмы Гаусса, поскольку обратный проход не нужен. Рассмотрите случай, когда получилась верхнетреугольная матрица, без строки, вида `(0, 0, 0.....0|α)`, на лекциях и семинарах вы разбирали такие случаи, в коде вам необходимо будет учесть этот случай (подсказка: если число переменных больше числа уравнений и у в верхнетреугольной матрицы нет строки вида `(0, 0, 0.....0|α)`, то эта система имеет бесконечное количество решений).


На вход функции подается матрица после алгоритма Гаусса, проверить матрицу на все случаи, если система имеет одно решение или бесконечное количество, то применить алгоритм Гаусса, вывести один из трех ответов:


*   Не имеет решений, в случае, если есть строка вида `(0, 0, 0.....0|α)` -> вернуть None
*   Общее решение СЛАУ, если решений бесконечное количество -> вернуть 'inf'
*   Единственное решение -> вернуть решение

In [167]:
from sympy.solvers.solveset import linsolve

def get_solution(S: np.array):
    A, b = S[:, :-1], S[:, -1]
    null_A_mask, null_b_mask = np.all(A == 0, axis=1), (b == 0)
    if np.any(null_A_mask & ~null_b_mask):
        return None
    null_rows_mask = np.all(A == 0, axis=1)
    if A[~null_rows_mask].shape[0] < A[~null_rows_mask].shape[1]:
        return 'inf'
    return b

for d in one_solution:
    my_sol = get_solution(gaussian_elimination(d['A'], d['b'])).ravel()
    numpy_sol = np.linalg.solve(d['A'], d['b']).ravel()
    assert np.allclose(my_sol, numpy_sol)

for d in no_solutions:
    my_sol = get_solution(gaussian_elimination(d['A'], d['b']))
    assert my_sol is None

for d in infinite_solutions:
    my_sol = get_solution(gaussian_elimination(d['A'], d['b']))
    assert my_sol == 'inf'

## Часть 5. Время(5 баллов)

Питон мотивирует пользоваться библиотечными функциями, когда они доступны, а не писать собственные. Библиотечные функции основаны на современных алгоритмах, обычно пишутся на C++ или Fortran, а кроме того, оптимизированы для работы на многопроцессорных устройствах, так что обогнать эти решения просто так вы не сможете.

Попробуйте убедиться в этом самостоятельно. Напишите функцию `my_det`, которая вычисляет определитель матрицы с помощью элементарных преобразований над строками. Функция должна выкидывать `ValueError` в случаях, если матрица не является квадратной.

In [ ]:
def my_det(X):
    '''
    Parameters
    ----------
    X : array_like

    Returns
    -------
    det : float
        Determinant of `a`.
    '''

    # Your code here

    return det

Простая проверка:

In [ ]:
# Запустите этот блок кода
X = np.array([[0,0,1], [0,1,0], [1,0,0]])
print(X)
print(my_det(X))

На случай, если нам просто повезло с этой матрицей, имеет смысл написать чуть более хитрые тесты. Мы сгенерируем несколько случайных матриц $8\times8$ с помощью функции `numpy.random.rand` и сравним ответ, выдаваемый нашей функцией, с настоящим определителем (результатом работы библиотечной функции `sympy.Matrix.det`):

In [ ]:
# Запустите этот блок кода
for _ in range(10):
    X = np.random.rand(8,8)
    M = sp.Matrix(X)
    if np.abs(my_det(X) - M.det()) > 1e-6:
        print('FAILED')

Если вы ни разу не получили `FAILED`, то ваша функция работает правильно.

Теперь давайте сравним скорость работы вашей функции и библиотечной функции `det` из пакета `sympy`. В Питоне есть несколько способов измерения времени; мы воспользуемся декоратором `%timeit`.

Написав его перед функцией, он запускает её некоторое количество раз, выбирает три случайных запуска и возвращает длительность самого быстрого из них. Модификатор `-o` между декоратором и функцией позволяет сохранять результаты работы декоратора в переменную.

Следующий блок кода может работать долго, наберитесь терпения.

In [ ]:
# Запустите этот блок кода
lib_times = []
my_times = []
dimensions = [10, 100, 1000]
for dim in dimensions:
    S = np.random.rand(dim, dim)
    M = sp.Matrix(S)
    res_lib = %timeit -o M.det()
    lib_times.append(res_lib.best)
    res_my = %timeit -o my_det(A)
    my_times.append(res_my.best)

plt.plot(dimensions, lib_times, color='blue', label='Library function')
plt.plot(dimensions, my_times, color='red', label='My function')
plt.title('My function vs library function, log y scale')
plt.ylabel('Time')
plt.xlabel('Matrix dimension')
plt.legend()

У вас должны были получиться графики, показывающие, как растёт с ростом размерности матрицы время вычисления определителя. Поскольку они вышли не больно-то красивыми, мы нарисуем их в *логарифмическом масштабе* по оси у:

In [ ]:
# Запустите этот блок кода
plt.semilogy(dimensions, lib_times, color='blue', label='Library function')
plt.semilogy(dimensions, my_times, color='red', label='My function')
plt.title('My function vs library function, log y scale')
plt.ylabel('Time')
plt.xlabel('Matrix dimension')
plt.legend()

Вы можете убедиться, что библиотечная функция работает *гораздо* быстрее.